name: New Test
description: Create a new testcase
title: "⚙️[Test] Title"
labels: ["test"]
body:
- type: textarea
  attributes:
    label: "測試功能API、函數等(必填)"
    description: 描述需要測試的功能例如URL或具體哪個函數等
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: "測試方式(必填)"
    description: 描述測試的方式例如單元測試、集成測試、E2E測試等
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: "預期行為(必填)"
    description: 簡單描述原本預期會發生什麼事情
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: 其他補充
    description: |
      任何連結、截圖或影片等補充訊息，都可以寫在這裡。
      提示：可以點擊此區域以突出顯示，然後拖入圖片或相關文件。
  validations:
    required: false